#!/bin/sh
# The README's file chooser: a directory of several hundred pictures in a
# 1000x600 window, Ctrl+P, a few letters typed and one chosen; then Ctrl+P
# again and a file asked for by its number.
#
#   ./fuzzy_finder            on images/birds
#   ./fuzzy_finder DIR        on another directory

. "$(dirname "$0")/lib.sh"

open 1000 600 "${1:-$ROOT/images/birds}"

record "fuzzy_finder.mp4"
started=$(since_record)
press ctrl+p
sleep 1
keys g y r
sleep 1
keys Return
sleep 1
press ctrl+p
keys colon 4 0 0
sleep 1
keys Return
sleep 1
film=$(cut)
close
gif "$film" "fuzzy_finder.gif" 800 "$started"
